---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  chart:
    spec:
      chart: tdarr
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-home-lab
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    env:
      TZ: ${TIMEZONE}
      PUID: "1000"
      PGID: "1000"

    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          hajimari.io/icon: simple-icons:jellyfin
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Conditional Transcoding Application
          gethomepage.dev/group: Media Management
          gethomepage.dev/icon: tdarr.png
          gethomepage.dev/name: Tdarr
        hosts:
          - host: &host "tdarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: 8265
        tls:
          - hosts:
              - *host

    node:
      enabled: true
      id: node
      resources:
        requests:
          gpu.intel.com/i915: 1
          cpu: 100m
          memory: 512Mi
        limits:
          gpu.intel.com/i915: 1
          memory: 8Gi

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/tdarr/config
        mountPath: /app/config

      data:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/tdarr/data
        mountPath: /app/server

      media:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data/media

      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
