apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: valheim-k8s
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/lucianjones/valheim-k8s
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
