---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
