---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rdt-client
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        containers:
          main:
            strategy: RollingUpdate
            image:
              repository: rogerfar/rdtclient
              tag: 2.0.79
            env:
              PUID: &id "1000"
              PGID: *id
              TZ: ${TIMEZONE}

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 6500
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 3000Mi

    defaultPodOptions:
      podSecurityContext:
        runAsUser: *id
        runAsGroup: *id
        fsGroup: *id
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:download-box
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Real Debrid Download Client
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: rdt-client.png
          gethomepage.dev/name: RDT
          gethomepage.dev/widget.type: "qbittorrent"
          gethomepage.dev/widget.url: "http://rdt-client.${SECRET_DOMAIN}"

        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/rdtclient
        globalMounts:
          - path: /data/db
            readOnly: false

      downloads:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data/downloads
        globalMounts:
          - path: /data/downloads
