---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: community.general
    version: 10.7.7
  - name: community.sops
    version: 2.2.7
  - name: kubernetes.core
    version: 5.4.1
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.6.2
