---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 5.1.2
  - name: community.general
    version: 10.7.4
  - name: community.sops
    version: 2.2.3
  - name: kubernetes.core
    version: 5.4.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.6.1
