---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      jellyseerr:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: 1.9.2
            env:
              PUID: 1000
              PGID: 1000
              TZ: ${TIMEZONE}

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 5055
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2000Mi

            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:jellyfish
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Request Management
          gethomepage.dev/group: Media
          gethomepage.dev/icon: jellyseerr.png
          gethomepage.dev/name: Jellyseerr
          gethomepage.dev/widget.type: "jellyseerr"
          gethomepage.dev/widget.url: "http://jellyseerr.media:5055"
          gethomepage.dev/widget.key: "${JELLYSEERR_API_KEY}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/jellyseerr
        globalMounts:
          - path: /app/config
            readOnly: false
