---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellystat
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      jellystat:
        strategy: RollingUpdate
        containers:
          db:
            image:
              repository: postgres
              tag: 15.2
            env:
              POSTGRES_DB: jfstat
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres

          app:
            image:
              repository: docker.io/cyfershepard/jellystat
              tag: 1.1.0
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_IP: db
              POSTGRES_PORT: 5432
              JWT_SECRET: example

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi

    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: jellystat
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 3000

    ingress:
      app:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # hajimari.io/icon: simple-icons:jellyfin
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/description: Media Server
          # gethomepage.dev/group: Media
          # gethomepage.dev/icon: jellyfin.png
          # gethomepage.dev/name: Jellyfin
          # gethomepage.dev/widget.type: "jellyfin"
          # gethomepage.dev/widget.url: "http://jellyfin.media:8096"
          # gethomepage.dev/widget.key: "${JELLYFIN_API_KEY}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      backup:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/jellystat
        globalMounts:
          - path: /app/backend/backup-data
            readOnly: false
