apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:kJ8+/ehYO5HkxPPSHHWtFPdX6U+4T8uid8SnoXq4UTxCfYw2,iv:MCzLnNl8C8RJ9BnvZ656ZyeNkScT0xEPrJ7VSzsakfY=,tag:vyBQMbqpVNPD7zjCmcHq2Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:sU9jMOBT5C8HJt+RR77II3vjpSujJGMKCLLNLuMf7hLsKvhmCwj6nhljKeqmUQEcwkvrbzmb74NZfSxjUbJPun6NskQR6sPqIpnqOMgtZDbrFKn5amy7tz1z+6WPn3Pc4F/PmNwtCLT0hTVYfp3ZdesfthPLPjD6bx+FpfjUxdUij/UTe8Ya5fhM6plC46uVbHEfd3ecBRMFZw/+ak4dAvZcxSZqj3MZwSzsdOvPUw==,iv:XlAEwO2/GlVrk1viz2fSf1/zG/sANU7/KShwuiw2TJQ=,tag:MI/ZVL3UnsotPy4wLn2V/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2f9q2xvr8u7neqck0zc27wht8e8sjsqz090285c9kslnr64s4jsq2rq7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWE12MlJVZlJhSW9PK24w
            YlNYZUVVUUIxYTdRN1RaeVEwTXNwU3duaUM4CkRMTkpjVTFBQXNPRzZyZUl3Njl5
            bFNqTlF4aTJiSUJseXpYWkw5VE1sOVEKLS0tIC9Tc24wYzlray84YmhqUDRBNkov
            MVUvTEtqZjEvYzdrdVkrMm9zN2I1dUUKuHzvCNAwY8p9R2a96vIfb3iJYInFMer2
            b39qtS9ueYD9VrSCBLJu8ziphQu+XUHE4QIfaebj8hw30NitTWNhMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T16:37:21Z"
    mac: ENC[AES256_GCM,data:V8U4mF6e6yg+Za5ZoClMjcnk/YkNeR/1//nO9LLjk3WP0rJxcSSHbPoOu1jBwyj0oAIqTn1V3BbHKsH8EA3ZgE9QJDjUPeZZjI8EBjuE9uiWs47YBQExlJS+icsF3TX9XV5RcQ8CeCqI+N5DlQpE9QyDPxGXnO1sKvgcWqb1Qzk=,iv:/EFCzE+dqqKVx2CGSEa0WcZUoNjO03ozmOBtWNITThM=,tag:aub7kaO78cKrybeSDNUw/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
