apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:is5TEtLQuHaaeVRiSABJ2sCwloP7GG17,iv:OfT4tqb7E7jH1s0HT2649W9y+tQ3j6RamXX5Hmzfu9I=,tag:VqAI6O829EsuG5B+dIT9Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2f9q2xvr8u7neqck0zc27wht8e8sjsqz090285c9kslnr64s4jsq2rq7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYWtyNHFWUjNydU9MTDdL
            TEFzd3oxaE1MWU5EQjdlMUd0c2pGM2JUMGpzCnhKZEVyS1c3OFVLckx4UWdyZ1J2
            T0QzUE5CWE9DMjlvOHZ5VGErTVEvcjQKLS0tIEVmRnh4Q2liaTZ2ckhiT3dtVjdh
            SzJTQkpBaytPUHVlQUZLeDJHem1ZL2cKrSlc/q64EtPdZ8hpY6dkRGSGK2FWMauh
            xmF9c0qkCTDf6lchJVrjsVWhPjsAfvoLElh/yhShmli3VkLSaxcleA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T16:37:19Z"
    mac: ENC[AES256_GCM,data:N91qWqCJcP1yhVtGCZOGXZDxKe2pWVizxZgVc31zmrZJWLUDaFY1cYPuOMAuMGI+D/9vr12d/wcVRt871dncT+GRZ+JBmcJkGxa6jQcYDWCjfhWXIoWD4DQF3UchxT3p9SWve++GUtCO5Dqdw+vFtbEYPs1XhsZniih3Dx4WpRY=,iv:gC6RqRmfEQWfe+63PE6WJOyvM3mcouTVGwDNb6/9S04=,tag:Vu7drINtPS3oDnUHq8j2HQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
