---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      jellyfin:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.9.7
            env:
              TZ: ${TIMEZONE}
              JELLYFIN_PublishedServerUrl: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
              # JELLYFIN_FFmpeg__probesize: 50000000
              # JELLYFIN_FFmpeg__analyzeduration: 50000000

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi

    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: simple-icons:jellyfin
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Media Server
          gethomepage.dev/group: Media
          gethomepage.dev/icon: jellyfin.png
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/widget.type: "jellyfin"
          gethomepage.dev/widget.url: "http://jellyfin:8096"
          gethomepage.dev/widget.key: "${JELLYFIN_API_KEY}"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/jellyfin
        globalMounts:
          - path: /config
            readOnly: false

      media:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data/media
        globalMounts:
          - path: /data/media

      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcode

      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /cache
