---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-values
data:
  values.yaml: |
    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: true
    bpf:
      masquerade: true
    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      name: home-cluster
      id: 1
    cni:
      exclusive: false
    endpointRoutes:
      enabled: true
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: "${CLUSTER_CIDR}"
    k8sServiceHost: "${KUBE_VIP_ADDR}"
    k8sServicePort: 6443
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: true
      # https://github.com/cilium/cilium/issues/26586
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      algorithm: maglev
      mode: snat
    localRedirectPolicy: true
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
