---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.17.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - name: cilium-values
      kind: ConfigMap
      valuesKey: values.yaml
  values:
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          annotations:
            grafana_folder: Cilium
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: external
          annotations:
            external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
            hajimari.io/icon: simple-icons:cilium
            gethomepage.dev/enabled: "true"
            gethomepage.dev/description: A networking and security observability platform
            gethomepage.dev/group: Admin
            gethomepage.dev/icon: cilium.png
            gethomepage.dev/name: Hubble
          hosts:
            - "hubble.${SECRET_DOMAIN}"
          tls:
            - hosts:
                - "hubble.${SECRET_DOMAIN}"
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
