apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:ureLq74tbtTAzfU=,iv:A98GA6WVz1QrhBm407hB9j58jaMrMbHhCPTaW6vkVv4=,tag:vjOWvbjOl3iaPLN7Szc+vQ==,type:str]
    admin-user: ENC[AES256_GCM,data:sCsIRgc=,iv:X0txlokihIF7A5Udgq3lIy6NCv0NgonHN9wtHhJ6t9A=,tag:UwhQ1NcT+lNW37uGyYhYEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2f9q2xvr8u7neqck0zc27wht8e8sjsqz090285c9kslnr64s4jsq2rq7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeCtGZGYwd0QzcWtiWndQ
            ck9raW1JeS84ZnBvMDM0MDVQMi9QWWlMQkI4CjFKNThZT21nQ0E3Wkd1V05HcUFk
            Qk1tLzE5Z25PUjZoamtScDZkRG42ejAKLS0tIG1vbmhwWmtWeVVQN01jV3QwNlo5
            dGdlWHpCWEZMd3c0cGhKMnFXeEl4RGsKSOMonMeR0MR63vOrNits1QGakdyQM68d
            yYQ9TZ/bWyeWMpsYs37+P47FAz96BS7hVcQ/A7F6miCB/APB/xp8XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T16:37:28Z"
    mac: ENC[AES256_GCM,data:Nl8qsYvmTvjlnFyhIAzwy4q9eGX9yHp2hK29d03eJygOKNEhEHxee/ycc18OIB8gv6SnsnF0EWtva4IuFlnBdanlGTfoWiF3bzlt+qEG5hUAremnZ1MFUwIsxrznnLCzLIEAZHKTLoWudPvdbrRA6cg7lYCxrr0YNBidg6egQdg=,iv:28P1mIOPGStsUWeSEkH2Sw1W2dtGopJZSyfhP2MAoxc=,tag:7eR2oAxHYPWjwB5WyGsPbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
