---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            strategy: RollingUpdate
            image:
              repository: linuxserver/sonarr
              tag: 4.0.0-develop
            env:
              TZ: ${TIMEZONE}
              COMPlus_EnableDiagnostics: "0"
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 8989
              SONARR__APPLICATION_URL: "https://sonarr.${SECRET_DOMAIN}"
              SONARR__LOG_LEVEL: info
              DOCKER_MODS: ghcr.io/themepark-dev/theme.park:sonarr
              TP_THEME: overseerr
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2000Mi
    defaultPodOptions:
      podSecurityContext:
        privileged: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          hajimari.io/icon: mdi:television-classic
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: TV Manager
          gethomepage.dev/group: Media Management
          gethomepage.dev/icon: sonarr.png
          gethomepage.dev/name: Sonarr
          gethomepage.dev/pod-selector: ""
          gethomepage.dev/widget.type: "sonarr"
          gethomepage.dev/widget.url: "http://sonarr.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "${SONARR_API_KEY}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/sonarr
        globalMounts:
          - path: /config
            readOnly: false

      media:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data
        globalMounts:
          - path: /mnt/data
