---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      sonarr:
        containers:
          app:
            strategy: RollingUpdate
            image:
              repository: linuxserver/sonarr
              tag: 4.0.6-develop
            env:
              PUID: &id "1000"
              PGID: *id
              TZ: ${TIMEZONE}
              DOCKER_MODS: ghcr.io/themepark-dev/theme.park:sonarr
              TP_THEME: overseerr

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 8989
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2000Mi

    defaultPodOptions:
      podSecurityContext:
        runAsUser: *id
        runAsGroup: *id
        fsGroup: *id
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        controller: sonarr
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:television-classic
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: TV Manager
          gethomepage.dev/group: Media Management
          gethomepage.dev/icon: sonarr.png
          gethomepage.dev/name: Sonarr
          gethomepage.dev/widget.type: "sonarr"
          gethomepage.dev/widget.url: "http://sonarr.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "${SONARR_API_KEY}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/sonarr
        globalMounts:
          - path: /config
            readOnly: false

      data:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data
        globalMounts:
          - path: /data
