---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        containers:
          main:
            strategy: RollingUpdate
            image:
              repository: linuxserver/radarr
              tag: 5.2.6
            env:
              PUID: &id ${MEDIA_ID}
              PGID: *id
              TZ: ${TIMEZONE}
              DOCKER_MODS: ghcr.io/themepark-dev/theme.park:radarr
              TP_THEME: overseerr

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 7878
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2000Mi

    defaultPodOptions:
      podSecurityContext:
        runAsUser: *id
        runAsGroup: *id
        fsGroup: *id
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          hajimari.io/icon: mdi:filmstrip
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Movie Manager
          gethomepage.dev/group: Media Management
          gethomepage.dev/icon: radarr.png
          gethomepage.dev/name: Radarr
          gethomepage.dev/widget.type: "radarr"
          gethomepage.dev/widget.url: "http://radarr.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "${RADARR_API_KEY}"

        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /mnt/data/configs/radarr
        globalMounts:
          - path: /config
            readOnly: false

      data:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data
        globalMounts:
          - path: /data
