apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Kxa5GlqBSf5q3XhH,iv:vm0CUcebx8TBzrGCzCcKxzrEc/zoHm9dSNTggGapK/w=,tag:3a7UnUJJ5riR9ONrs0oI5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2f9q2xvr8u7neqck0zc27wht8e8sjsqz090285c9kslnr64s4jsq2rq7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WmExdldST0I3WDgvOUd6
            emRnWmdleUI1SWFaMUc1VSsyTzVlZWNUUm40CkRQdWprSHVEUEI5TTlXNC8rN01n
            WTVOTDFzLzZpbzJrc3N4K2RmcHJ0S2MKLS0tIDIrOW8zRkp3RWF2MjloZFFjS1Rj
            bmUvZmgzRXZzWEZFWTNsd25vTWx5RkEKVpAzgTj0c4gyUfPMFTAgaRcYH9P0Pe7M
            gYH5Hohqui3wL0JYdFJUza8Jg8oze3RGDcZLisgCQ9fiIPLBdrN4ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T16:37:18Z"
    mac: ENC[AES256_GCM,data:wzyN88zrdbPKSj41x6+hrnAQumEmFUf4VPljYNW24wgkFlwCS6dcQHG4h/Ai3BbNsIeqMIo/nMNOgKEUk2MZkTlHvS5cp8PSzXRyqOEgRkGlda5nQ8cui8BZurkzFEg33iiJqTnYUG7BBJIkQ151jbou362tGoot0kL/uVFeS8A=,iv:Fc3q57mRkiQ1jcMYEtcqBVXWnlK/tT+R8TmI+DuU6kQ=,tag:0rnFLclUAcvPHn01hGfeSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
