---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            strategy: RollingUpdate
            image:
              repository: linuxserver/plex
              tag: 1.32.8
              env:
                TZ: ${TIMEZONE}
                PLEX_CLAIM: claim-yU2HuexmhN2R3Uc42Wfv
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        type: LoadBalancer
        # loadBalancerIP: *loadBalancerIP
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          # external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: simple-icons:plex
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Media Server
          gethomepage.dev/group: Media
          gethomepage.dev/icon: plex.png
          gethomepage.dev/name: Plex
          gethomepage.dev/pod-selector: ""
          # gethomepage.dev/widget.type: "plex"
          # gethomepage.dev/widget.url: "http://plex.${SECRET_DOMAIN}"
          # gethomepage.dev/widget.key: "${JELLYFIN_API_KEY}"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      media:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data/media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/plex
        globalMounts:
          - path: /config
            readOnly: false
