---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: organizr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      organizr:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: organizr/organizr
              tag: latest
            env:
              PUID: &id 1000
              PGID: *id
              TZ: ${TIMEZONE}

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2000Mi

    defaultPodOptions:
      securityContext:
        privileged: true
        runAsUser: *id
        runAsGroup: *id
        fsGroup: *id
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        controller: organizr
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: fluent:organization-20-regular
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/organizr
        globalMounts:
          - path: /config
            readOnly: false
