---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: Revision

  interval: 3m
  driftDetection:
    mode: enabled
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        containers:
          main:
            strategy: RollingUpdate
            image:
              repository: youegraillot/lidarr-on-steroids
              tag: 1.5.1
            env:
              PUID: &id "1000"
              PGID: *id
              CLEAN_DOWNLOADS: true

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 8686
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2000Mi

    defaultPodOptions:
      podSecurityContext:
        runAsUser: *id
        runAsGroup: *id
        fsGroup: *id
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        ports:
          http:
            port: *port
          deemix:
            port: 6595

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          # external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Music Manager
          gethomepage.dev/group: Media Management
          gethomepage.dev/icon: lidarr.png
          gethomepage.dev/name: Lidarr
          gethomepage.dev/widget.type: "lidarr"
          gethomepage.dev/widget.url: "http://lidarr.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "${LIDARR_API_KEY}"

        hosts:
          - host: &lidarrHost "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
          - host: &deemixHost deemix.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: deemix
        tls:
          - hosts:
              - *lidarrHost
              - *deemixHost

    persistence:
      lidarrConfig:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/lidarr
        globalMounts:
          - path: /config
            readOnly: false

      deemixConfig:
        enabled: true
        type: hostPath
        hostPath: /home/lucian/configs/deemix
        globalMounts:
          - path: /config_deemix
            readOnly: false

      downloads:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data/downloads/lidarr
        globalMounts:
          - path: /downloads

      music:
        enabled: true
        type: nfs
        server: 10.10.10.10
        path: /mnt/data/media/music
        globalMounts:
          - path: /music
